name: "macOS"
on:
  pull_request:
  push:
    paths-ignore:
      - .gitignore
      - README.md
      - fetch*
  schedule:
    # TIP: Choose a random time here so not all repositories are build at once:
    # https://www.random.org/clock-times/?num=1&earliest=01%3A00&latest=08%3A00&interval=5&format=html&rnd=new
    - cron: "35 5 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
      - name: Install nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      - name: Show nixpkgs version
        run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - name: Setup cachix
        uses: cachix/cachix-action@v10
        with:
          name: jechol
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build nix packages
        run: nix-build . -A erlang -A elixir
        env:
          NIXPKGS_ALLOW_INSECURE: 1
